version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: symfony4-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8002:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: symfony4-phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql

    webserver:
      image: nginx:alpine
      container_name: symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8020:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

